module.exports = {
  arToId: {
  "كتب": "menulis",
  "كاتب": "penulis",
  "مكتوب": "tertulis",
  "كتاب": "buku",
  "كتابة": "penulisan",
  "مكتب": "kantor",
  "مكتبة": "perpustakaan",
  "كبير": "besar",
  "صغير": "kecil",
  "جميل": "indah",
  "بيت": "rumah",
  "مدرسة": "sekolah",
  "جامعة": "universitas",
  "مستشفى": "rumahsakit",
  "مدينة": "kota",
  "قرية": "desa",
  "عالم": "ilmuwan",
  "علم": "ilmu",
  "يعلم": "mengetahui",
  "يعلمون": "merekamengetahui",
  "ذهب": "pergi",
  "يذهب": "pergi (sedang)",
  "ذاهب": "sedangpergi",
  "ذهبوا": "merekapergi",
  "رجع": "kembali",
  "يرجع": "kembali (sedang)",
  "راجع": "yangkembali",
  "رجوع": "kembalinya",
  "اكل": "makan",
  "يأكل": "sedangmakan",
  "مأكول": "makananyangdimakan",
  "شرب": "minum",
  "يشرب": "sedangminum",
  "مشروب": "minuman",
  "درس": "belajar",
  "يدرس": "sedangbelajar",
  "مدرس": "guru",
  "تعليم": "pendidikan",
  "معلم": "pengajar",
  "سلام": "perdamaian",
  "سلامة": "keselamatan",
  "مسلم": "muslim",
  "اسلام": "islam",
  "سلام عليكم": "assalamualaikum",
  "كيف حالك": "apakabarmu",
  "بخير": "baik",
  "لغة": "bahasa",
  "عربي": "arab",
  "اندونيسي": "indonesia",
  "ترجمة": "terjemahan",
  "مترجم": "penerjemah",
  "عمل": "kerja",
  "عامل": "pekerja",
  "شركة": "perusahaan",
  "مال": "uang",
  "غني": "kaya",
  "فقير": "miskin",
  "وقت": "waktu",
  "ساعة": "jam",
  "يوم": "hari",
  "أسبوع": "minggu",
  "شهر": "bulan",
  "سنة": "tahun",
  "سماء": "langit",
  "أرض": "bumi",
  "شمس": "matahari",
  "قمر": "bulan (moon)",
  "نجمة": "bintang",
  "بحر": "laut",
  "نهر": "sungai",
  "مطر": "hujan",
  "جو": "cuaca",
  "هواء": "udara",
  "حار": "panas",
  "بارد": "dingin",
  "كاتبون": "parapenulis",
  "كتّاب": "parapenulis (jamak)",
  "كتابات": "tulisan-tulisan",
  "كتاباته": "tulisan-tulisannya",
  "مكتوبات": "surat-surat",
  "كتابي": "bersifatbuku / kitabku",
  "كتابية": "tertulis / dokumenter",
  "كتابيون": "kaumliterasi",
  "كاتبتي": "penulisperempuanku",
  "كتّابِي": "penulisanku",
  "إجابة": "jawaban",
  "سؤال": "pertanyaan",
  "أسئلة": "pertanyaan-pertanyaan",
  "جواب": "jawaban",
  "يجيب": "menjawab",
  "مجيب": "yangmenjawab",
  "مجاوب": "yangmerespon",
  "إجابات": "jawaban-jawaban",
  "سائل": "yangbertanya",
  "مسؤول": "bertanggungjawab",
  "مسؤولية": "tanggungjawab",
  "مسؤوليات": "tanggungjawab (jamak)",
  "مسألة": "perkara / persoalan",
  "مسائل": "perkara-perkara",
  "بحث": "penelitian",
  "يبحث": "mencari / meneliti",
  "باحث": "peneliti",
  "معلومات": "informasi",
  "معلومة": "sebuahinformasi",
  "علماء": "parailmuwan",
  "أعلم": "palingtahu",
  "تعلم": "belajar",
  "يتعلم": "sedangbelajar",
  "تعليمات": "instruksi",
  "مكتشف": "penemu",
  "اكتشاف": "penemuan",
  "يكتشف": "menemukan",
  "مفهوم": "konsep",
  "يفهم": "memahami",
  "فهم": "pemahaman",
  "مفهومات": "konsep-konsep",
  "شرح": "penjelasan",
  "يشرح": "menjelaskan",
  "مشروح": "yangdijelaskan",
  "مقالات": "artikel-artikel",
  "مقال": "artikel",
  "كاتب مقال": "penulisartikel",
  "موضوع": "topik",
  "مواضيع": "topik-topik",
  "نقاش": "diskusi",
  "يناقش": "berdiskusi",
  "مناقشة": "diskusi",
  "لغة عربية": "bahasaArab",
  "لغة اندونيسية": "bahasaIndonesia",
  "لغة إنجليزية": "bahasaInggris",
  "لغات": "bahasa-bahasa",
  "ترجمات": "terjemahan-terjemahan",
  "مترجم فوري": "penerjemahlangsung",
  "ترجمة حرفية": "terjemahanharfiah",
  "ترجمة معنوية": "terjemahanmaknawi",
  "ترجمة صوتية": "terjemahansuara",
  "كلمة": "kata",
  "كلمات": "kata-kata",
  "جملة": "kalimat",
  "جمل": "kalimat-kalimat",
  "نص": "teks",
  "نصوص": "teks-teks",
  "فعل": "katakerja",
  "أفعال": "katakerja (jamak)",
  "اسم": "katabenda",
  "أسماء": "nama-nama / katabenda",
  "صفة": "sifat",
  "صفات": "sifat-sifat",
  "حال": "keterangan",
  "أحوال": "kondisi-kondisi",
  "زمان": "waktu",
  "مكان": "tempat",
  "فعل ماض": "fi'ilmadhi",
  "فعل مضارع": "fi'ilmudhari’",
  "أمر": "perintah",
  "نهي": "larangan",
  "مصدر": "mashdar",
  "مصادر": "jamakmashdar",
  "حرف": "huruf",
  "حروف": "huruf-huruf",
  "حرف جر": "hurufjar",
  "أداة": "sarana / alat",
  "أدوات": "alat-alat",
  "أيام": "hari-hari",
  "نهار": "siang",
  "ليل": "malam",
  "صباح": "pagi",
  "مساء": "sore",
  "ظلام": "kegelapan",
  "نور": "cahaya",
  "ضوء": "cahaya (lebihumum)",
  "ظلال": "bayangan",
  "ظل": "naungan / bayangan",
  "سماء دنيا": "langitdunia",
  "مجرة": "galaksi",
  "كون": "alamsemesta",
  "وجود": "eksistensi",
  "حياة": "kehidupan",
  "حي": "hidup",
  "يعيش": "hidup (katakerja)",
  "موت": "kematian",
  "ميت": "orangmati",
  "مقبرة": "kuburan",
  "قبر": "makam",
  "قلب": "hati",
  "قلوب": "hati-hati",
  "روح": "jiwa",
  "أرواح": "roh-roh",
  "عقل": "akal",
  "عقول": "akal-akal",
  "فكرة": "ide",
  "أفكار": "ide-ide",
  "إبداع": "kreativitas",
  "مبدع": "kreatif",
  "فن": "seni",
  "فنون": "seni-seni",
  "موسيقى": "musik",
  "غناء": "nyanyian",
  "يغني": "menyanyi",
  "مغنٍ": "penyanyi",
  "رقص": "tarian",
  "يرقص": "menari",
  "صوت": "suara",
  "أصوات": "suara-suara",
  "هدوء": "ketenangan",
  "صخب": "keramaian",
  "ريح": "angin",
  "رياح": "angin-angin",
  "عاصفة": "badai",
  "عواصف": "badai-badai",
  "طعام": "makanan",
  "أطعمة": "makanan-makanan",
  "شراب": "minuman",
  "مشروبات": "minuman-minuman",
  "خبز": "roti",
  "أرز": "nasi",
  "ماء": "air",
  "لبن": "susu",
  "قهوة": "kopi",
  "شاي": "teh",
  "سكر": "gula",
  "ملح": "garam",
  "فلفل": "lada",
  "بيض": "telur",
  "دجاج": "ayam",
  "لحم": "daging",
  "سمك": "ikan",
  "خضار": "sayuran",
  "فاكهة": "buah",
  "تفاح": "apel",
  "موز": "pisang",
  "برتقال": "jeruk",
  "عنب": "anggur",
  "بطيخ": "semangka",
  "فراولة": "stroberi",
  "سيارة": "mobil",
  "قطار": "kereta",
  "طائرة": "pesawat",
  "مطار": "bandara",
  "سفينة": "kapal",
  "ميناء": "pelabuhan",
  "دراجة": "sepeda",
  "شارع": "jalan",
  "طرق": "jalan-jalan",
  "جسر": "jembatan",
  "ممر": "lorong",
  "عاصمة": "ibukota",
  "منطقة": "area",
  "حديقة": "taman",
  "زهرة": "bunga",
  "أزهار": "bunga-bunga",
  "شجرة": "pohon",
  "غابة": "hutan",
  "صحراء": "padangpasir",
  "جبل": "gunung",
  "جبال": "gunung-gunung",
  "وادي": "lembah",
  "سهول": "padangluas",
  "مرتفعات": "daerahtinggi",
  "مياه": "air-air",
  "بحيرة": "danau",
  "ينبوع": "mataair",
  "بركان": "gunungberapi",
  "زلزال": "gempabumi",
  "مناخ": "iklim",
  "فصل": "musim",
  "فصول": "musim-musim",
  "ربيع": "musimsemi",
  "صيف": "musimpanas",
  "خريف": "musimgugur",
  "شتاء": "musimdingin",
  "ملابس": "pakaian",
  "قميص": "kemeja",
  "بنطال": "celana",
  "قبعة": "topi",
  "حذاء": "sepatu",
  "جورب": "kaoskaki",
  "معطف": "jas",
  "ثوب": "jubah",
  "عباءة": "abaya",
  "نظارة": "kacamata",
  "ساعة tangan": "jamtangan",
  "خاتم": "cincin",
  "هاتف": "telepon",
  "هاتف محمول": "hp",
  "حاسوب": "komputer",
  "حاسوب محمول": "laptop",
  "إنترنت": "internet",
  "موقع": "website",
  "برنامج": "program",
  "برمجة": "programming",
  "مطوّر": "developer",
  "بيانات": "data",
  "قاعدة بيانات": "database",
  "خادم": "server",
  "ملف": "file",
  "مجلد": "folder",
  "تحميل": "download",
  "رفع": "upload",
  "نظام": "system",
  "إعدادات": "pengaturan",
  "شبكة": "jaringan",
  "اتصال": "koneksi",
  "سريع": "cepat",
  "بطيء": "lambat",
  "جيد": "bagus",
  "سيئ": "buruk",
  "ممتاز": "hebat",
  "ضعيف": "lemah",
  "قوي": "kuat",
  "أحمر": "merah",
  "أزرق": "biru",
  "أخضر": "hijau",
  "أصفر": "kuning",
  "أسود": "hitam",
  "أبيض": "putih",
  "رمادي": "abu-abu",
  "برتقالي": "jingga",
  "وردي": "pink",
  "بنفسجي": "ungu",
  "ذهبي": "emas",
  "فضي": "perak",
  "بيتزا": "pizza",
  "معكرونة": "makaroni",
  "رز": "nasi",
  "سطح": "atap",
  "باب": "pintu",
  "نافذة": "jendela",
  "جدار": "tembok",
  "سقف": "plafon",
  "أرضية": "lantai",
  "مطبخ": "dapur",
  "حمام": "kamarmandi",
  "غرفة نوم": "kamartidur",
  "غرفة جلوس": "ruangtamu",
  "مكتب عمل": "mejakerja",
  "وسادة": "bantal",
  "بطانية": "selimut",
  "رف": "rak",
  "مرآة": "cermin",
  "سجادة": "karpet",
  "حديقة منزل": "tamanrumah",
  "مصباح يد": "senter",
  "ظرف": "amplop",
  "قلم رصاص": "pensil",
  "ورقة": "kertas",
  "ممحاة": "penghapus",
  "مبراة": "serutanpensil",
  "مقص": "gunting",
  "فرشاة شعر": "sikatrambut",
  "معجون أسنان": "odol",
  "مكيف هواء": "AC",
  "ريموت": "remote",
  "آلة موسيقية": "alatmusik",
  "طبيب": "dokter",
  "ممرضة": "perawat",
  "صيدلية": "apotek",
  "دواء": "obat",
  "مسكن الألم": "peredanyeri",
  "حقنة": "suntikan",
  "مطعم": "restoran",
  "وجبة": "makanan",
  "نادل": "pelayan",
  "طبخ": "memasak",
  "طبق": "hidangan",
  "حلوى": "dessert",
  "فطور": "sarapan",
  "غداء": "makansiang",
  "عشاء": "makanmalam",
  "نوم": "tidur",
  "استيقاظ": "bangun",
  "راحة": "istirahat",
  "تعب": "kelelahan",
  "قوة": "kekuatan",
  "سرعة": "kecepatan",
  "فرح": "kegembiraan",
  "حزن": "kesedihan",
  "غضب": "kemarahan",
  "خوف": "ketakutan",
  "دهشة": "keheranan",
  "سعادة": "kebahagiaan",
  "ابتسامة": "senyuman",
  "دموع": "airmata",
  "ضحك": "tawa",
  "مزاح": "bercanda",
  "صداقة": "persahabatan",
  "حب": "cinta",
  "زواج": "pernikahan",
  "عائلة": "keluarga",
  "أم": "ibu",
  "أب": "ayah",
  "ابن": "anaklaki-laki",
  "ابنة": "anakperempuan",
  "جد": "kakek",
  "جدة": "nenek",
  "عم": "paman (ayah)",
  "خال": "paman (ibu)",
  "عمة": "bibi (ayah)",
  "خالة": "bibi (ibu)",
  "جار": "tetangga",
  "صديق": "teman",
  "زميل": "rekankerja",
  "راتب": "gaji",
  "ترقية": "kenaikanjabatan",
  "خبرة": "pengalaman",
  "إجازة": "liburan",
  "خطة kerja": "rencanakerja",
  "مدير": "manajer",
  "شركة كبيرة": "perusahaanbesar",
  "شركة ناشئة": "start-up",
  "مستثمر": "investor",
  "مبيعات": "penjualan",
  "شراء": "pembelian",
  "تجارة": "perdagangan",
  "ربح": "keuntungan",
  "خسارة": "kerugian",
  "توصيل": "pengiriman",
  "مخزن": "gudang",
  "تخزين": "penyimpanan",
  "نمو": "pertumbuhan",
  "مؤشر": "index",
  "إحصاء": "statistik",
  "منحة": "beasiswa",
  "امتحان": "ujian",
  "نتيجة": "nilai",
  "مدرس خصوصي": "tutor",
  "قاعة": "gedungaula",
  "مختبر": "laboratorium",
  "إصابة": "cedera",
  "كسر": "patah",
  "التهاب": "radang",
  "عدوى": "infeksi",
  "ورم": "bengkak / tumor",
  "صداع": "sakitkepala",
  "دوخة": "pusing",
  "إغماء": "pingsan",
  "عطس": "bersin",
  "حساسية": "alergi",
  "تنفس": "pernapasan",
  "يتنفس": "bernapas",
  "تنفس صناعي": "ventilasi",
  "أوكسجين": "oksigen",
  "ضغط الدم": "tekanandarah",
  "نبض": "detaknadi",
  "برد شديد": "dinginsekali",
  "حر شديد": "panassekali",
  "عطش": "haus",
  "جوع": "lapar",
  "صوت جميل": "suaraindah",
  "صوت مرتفع": "suarakeras",
  "صوت منخفض": "suarapelan",
  "صدى suara": "gema",
  "مستوى عالٍ": "leveltinggi",
  "مستوى منخفض": "levelrendah",
  "حالة نشطة": "statusaktif",
  "حالة خاملة": "statuspasif",
  "إدارة الوقت": "manajemenwaktu",
  "تنظيم يومي": "rencanaharian",
  "تركيز عميق": "fokusmendalam",
  "تشتيت انتباه": "gangguanfokus",
  "مهام يومية": "tugasharian",
  "قائمة مهام": "daftartugas",
  "أولوية قصوى": "prioritastinggi",
  "جدول أسبوعي": "jadwalmingguan",
  "إنجاز سريع": "pencapaiancepat",
  "إنتاجية عالية": "produktivitastinggi",
  "تخطيط مسبق": "perencanaansebelumnya",
  "هدف طويل المدى": "tujuanjangkapanjang",
  "هدف قصير المدى": "tujuanjangkapendek",
  "مرحلة أولى": "tahappertama",
  "مرحلة نهائية": "tahapakhir",
  "خطوة خطوة": "selangkahdemiselangkah",
  "نتيجة نهائية": "hasilakhir",
  "حساب دقيق": "perhitungantepat",
  "مراجعة يومية": "evaluasiharian",
  "تطوير مستمر": "pengembanganberkelanjutan",
  "تحسين ذاتي": "perbaikandiri",
  "تنظيم ملفات": "pengaturanfile",
  "إدارة مشاريع": "manajemenproyek",
  "تواصل فعال": "komunikasiefektif",
  "حوار بنّاء": "dialogkonstruktif",
  "خلاف بسيط": "perbedaankecil",
  "اتفاق كامل": "kesepakatanpenuh",
  "عرض تقديمي": "presentation",
  "استشارة مهنية": "konsultasiprofesional",
  "مهمة رسمية": "tugasresmi",
  "شرح مفصل": "penjelasandetail",
  "معلومات دقيقة": "informasiakurat",
  "نقطة مهمة": "poinpenting",
  "مثال عملي": "contohpraktis",
  "ملخص عام": "ringkasanumum",
  "خلاصة نهائية": "kesimpulanfinal",
  "دعم فني": "dukunganteknis",
  "حلول جاهزة": "solusisiappakai",
  "إعداد تلقائي": "setupotomatis",
  "محاولة فاشلة": "percobaangagal",
  "إعادة محاولة": "cobalagi",
  "بيانات ناقصة": "datakurang",
  "بيانات صحيحة": "datavalid",
  "ملف ناقص": "filemissing",
  "ملف تالف": "filecorrupt",
  "تحميل ناجح": "downloadsukses",
  "رفع ناجح": "uploadsukses",
  "تثبيت ناجح": "installsukses",
  "إعداد ناجح": "setupsukses",
  "استعادة ناجحة": "restoreberhasil",
  "تشغيل تلقائي": "autorun",
  "إيقاف إجباري": "forcestop",
  "تجربة جديدة": "percobaanbaru",
  "واجهة جديدة": "antarmukabaru",
  "نسخة محدثة": "versiterbaru",
  "إصدار جديد": "rilisanbaru",
  "مستوى محترف": "levelprofesional",
  "إعدادات متقدمة": "pengaturanlanjutan",
  "واجهة بسيطة": "antarmukasimple",
  "واجهة معقدة": "antarmukakompleks",
  "نظام كامل": "sistemlengkap",
  "مكتمل 100٪": "selesai 100%",
  "جاهز للاستخدام": "siapdipakai",
  "سهل الاستخدام": "ramahpengguna",
  "متوافق مع الهاتف": "compatiblehp",
  "متوافق مع المتصفح": "compatiblebrowser",
  "يدعم iPhone": "mendukungiPhone",
  "يدعم Safari": "mendukungSafari",
  "بدون أخطاء": "tanpaerror",
  "بدون مشاكل": "tanpamasalah",
  "جاهز للنشر": "siapdeploy"
},

  idToAr: {
  "menulis": "كتب",
  "penulis": "كاتب",
  "tertulis": "مكتوب",
  "buku": "كتاب",
  "penulisan": "كتابة",
  "kantor": "مكتب",
  "perpustakaan": "مكتبة",
  "besar": "كبير",
  "kecil": "صغير",
  "indah": "جميل",
  "rumah": "بيت",
  "sekolah": "مدرسة",
  "universitas": "جامعة",
  "rumahsakit": "مستشفى",
  "kota": "مدينة",
  "desa": "قرية",
  "ilmuwan": "عالم",
  "ilmu": "علم",
  "mengetahui": "يعلم",
  "merekamengetahui": "يعلمون",
  "pergi": "ذهب",
  "pergi (sedang)": "يذهب",
  "sedangpergi": "ذاهب",
  "merekapergi": "ذهبوا",
  "kembali": "رجع",
  "kembali (sedang)": "يرجع",
  "yangkembali": "راجع",
  "kembalinya": "رجوع",
  "makan": "اكل",
  "sedangmakan": "يأكل",
  "makananyangdimakan": "مأكول",
  "minum": "شرب",
  "sedangminum": "يشرب",
  "minuman": "مشروب",
  "belajar": "درس",
  "sedangbelajar": "يدرس",
  "guru": "مدرس",
  "pendidikan": "تعليم",
  "pengajar": "معلم",
  "perdamaian": "سلام",
  "keselamatan": "سلامة",
  "muslim": "مسلم",
  "islam": "اسلام",
  "assalamualaikum": "سلام عليكم",
  "apakabarmu": "كيف حالك",
  "baik": "بخير",
  "bahasa": "لغة",
  "arab": "عربي",
  "indonesia": "اندونيسي",
  "terjemahan": "ترجمة",
  "penerjemah": "مترجم",
  "kerja": "عمل",
  "pekerja": "عامل",
  "perusahaan": "شركة",
  "uang": "مال",
  "kaya": "غني",
  "miskin": "فقير",
  "waktu": "وقت",
  "jam": "ساعة",
  "hari": "يوم",
  "minggu": "أسبوع",
  "bulan": "شهر",
  "tahun": "سنة",
  "langit": "سماء",
  "bumi": "أرض",
  "matahari": "شمس",
  "bulan (moon)": "قمر",
  "bintang": "نجمة",
  "laut": "بحر",
  "sungai": "نهر",
  "hujan": "مطر",
  "cuaca": "جو",
  "udara": "هواء",
  "panas": "حار",
  "dingin": "بارد",
  "parapenulis": "كاتبون",
  "parapenulis (jamak)": "كتّاب",
  "tulisan-tulisan": "كتابات",
  "tulisan-tulisannya": "كتاباته",
  "surat-surat": "مكتوبات",
  "bersifatbuku / kitabku": "كتابي",
  "tertulis / dokumenter": "كتابية",
  "kaumliterasi": "كتابيون",
  "penulisperempuanku": "كاتبتي",
  "penulisanku": "كتّابِي",
  "jawaban": "إجابة",
  "pertanyaan": "سؤال",
  "pertanyaan-pertanyaan": "أسئلة",
  "menjawab": "يجيب",
  "yangmenjawab": "مجيب",
  "yangmerespon": "مجاوب",
  "jawaban-jawaban": "إجابات",
  "yangbertanya": "سائل",
  "bertanggungjawab": "مسؤول",
  "tanggungjawab": "مسؤولية",
  "tanggungjawab (jamak)": "مسؤوليات",
  "perkara / persoalan": "مسألة",
  "perkara-perkara": "مسائل",
  "penelitian": "بحث",
  "mencari / meneliti": "يبحث",
  "peneliti": "باحث",
  "informasi": "معلومات",
  "sebuahinformasi": "معلومة",
  "parailmuwan": "علماء",
  "palingtahu": "أعلم",
  "instruksi": "تعليمات",
  "penemu": "مكتشف",
  "penemuan": "اكتشاف",
  "menemukan": "يكتشف",
  "konsep": "مفهوم",
  "memahami": "يفهم",
  "pemahaman": "فهم",
  "konsep-konsep": "مفهومات",
  "penjelasan": "شرح",
  "menjelaskan": "يشرح",
  "yangdijelaskan": "مشروح",
  "artikel-artikel": "مقالات",
  "artikel": "مقال",
  "penulisartikel": "كاتب مقال",
  "topik": "موضوع",
  "topik-topik": "مواضيع",
  "diskusi": "نقاش",
  "berdiskusi": "يناقش",
  "bahasaArab": "لغة عربية",
  "bahasaIndonesia": "لغة اندونيسية",
  "bahasaInggris": "لغة إنجليزية",
  "bahasa-bahasa": "لغات",
  "terjemahan-terjemahan": "ترجمات",
  "penerjemahlangsung": "مترجم فوري",
  "terjemahanharfiah": "ترجمة حرفية",
  "terjemahanmaknawi": "ترجمة معنوية",
  "terjemahansuara": "ترجمة صوتية",
  "kata": "كلمة",
  "kata-kata": "كلمات",
  "kalimat": "جملة",
  "kalimat-kalimat": "جمل",
  "teks": "نص",
  "teks-teks": "نصوص",
  "katakerja": "فعل",
  "katakerja (jamak)": "أفعال",
  "katabenda": "اسم",
  "nama-nama / katabenda": "أسماء",
  "sifat": "صفة",
  "sifat-sifat": "صفات",
  "keterangan": "حال",
  "kondisi-kondisi": "أحوال",
  "tempat": "مكان",
  "fi'ilmadhi": "فعل ماض",
  "fi'ilmudhari’": "فعل مضارع",
  "perintah": "أمر",
  "larangan": "نهي",
  "mashdar": "مصدر",
  "jamakmashdar": "مصادر",
  "huruf": "حرف",
  "huruf-huruf": "حروف",
  "hurufjar": "حرف جر",
  "sarana / alat": "أداة",
  "alat-alat": "أدوات",
  "hari-hari": "أيام",
  "siang": "نهار",
  "malam": "ليل",
  "pagi": "صباح",
  "sore": "مساء",
  "kegelapan": "ظلام",
  "cahaya": "نور",
  "cahaya (lebihumum)": "ضوء",
  "bayangan": "ظلال",
  "naungan / bayangan": "ظل",
  "langitdunia": "سماء دنيا",
  "galaksi": "مجرة",
  "alamsemesta": "كون",
  "eksistensi": "وجود",
  "kehidupan": "حياة",
  "hidup": "حي",
  "hidup (katakerja)": "يعيش",
  "kematian": "موت",
  "orangmati": "ميت",
  "kuburan": "مقبرة",
  "makam": "قبر",
  "hati": "قلب",
  "hati-hati": "قلوب",
  "jiwa": "روح",
  "roh-roh": "أرواح",
  "akal": "عقل",
  "akal-akal": "عقول",
  "ide": "فكرة",
  "ide-ide": "أفكار",
  "kreativitas": "إبداع",
  "kreatif": "مبدع",
  "seni": "فن",
  "seni-seni": "فنون",
  "musik": "موسيقى",
  "nyanyian": "غناء",
  "menyanyi": "يغني",
  "penyanyi": "مغنٍ",
  "tarian": "رقص",
  "menari": "يرقص",
  "suara": "صوت",
  "suara-suara": "أصوات",
  "ketenangan": "هدوء",
  "keramaian": "صخب",
  "angin": "ريح",
  "angin-angin": "رياح",
  "badai": "عاصفة",
  "badai-badai": "عواصف",
  "makanan": "طعام",
  "makanan-makanan": "أطعمة",
  "minuman-minuman": "مشروبات",
  "roti": "خبز",
  "nasi": "أرز",
  "air": "ماء",
  "susu": "لبن",
  "kopi": "قهوة",
  "teh": "شاي",
  "gula": "سكر",
  "garam": "ملح",
  "lada": "فلفل",
  "telur": "بيض",
  "ayam": "دجاج",
  "daging": "لحم",
  "ikan": "سمك",
  "sayuran": "خضار",
  "buah": "فاكهة",
  "apel": "تفاح",
  "pisang": "موز",
  "jeruk": "برتقال",
  "anggur": "عنب",
  "semangka": "بطيخ",
  "stroberi": "فراولة",
  "mobil": "سيارة",
  "kereta": "قطار",
  "pesawat": "طائرة",
  "bandara": "مطار",
  "kapal": "سفينة",
  "pelabuhan": "ميناء",
  "sepeda": "دراجة",
  "jalan": "شارع",
  "jalan-jalan": "طرق",
  "jembatan": "جسر",
  "lorong": "ممر",
  "ibukota": "عاصمة",
  "area": "منطقة",
  "taman": "حديقة",
  "bunga": "زهرة",
  "bunga-bunga": "أزهار",
  "pohon": "شجرة",
  "hutan": "غابة",
  "padangpasir": "صحراء",
  "gunung": "جبل",
  "gunung-gunung": "جبال",
  "lembah": "وادي",
  "padangluas": "سهول",
  "daerahtinggi": "مرتفعات",
  "air-air": "مياه",
  "danau": "بحيرة",
  "mataair": "ينبوع",
  "gunungberapi": "بركان",
  "gempabumi": "زلزال",
  "iklim": "مناخ",
  "musim": "فصل",
  "musim-musim": "فصول",
  "musimsemi": "ربيع",
  "musimpanas": "صيف",
  "musimgugur": "خريف",
  "musimdingin": "شتاء",
  "pakaian": "ملابس",
  "kemeja": "قميص",
  "celana": "بنطال",
  "topi": "قبعة",
  "sepatu": "حذاء",
  "kaoskaki": "جورب",
  "jas": "معطف",
  "jubah": "ثوب",
  "abaya": "عباءة",
  "kacamata": "نظارة",
  "jamtangan": "ساعة tangan",
  "cincin": "خاتم",
  "telepon": "هاتف",
  "hp": "هاتف محمول",
  "komputer": "حاسوب",
  "laptop": "حاسوب محمول",
  "internet": "إنترنت",
  "website": "موقع",
  "program": "برنامج",
  "programming": "برمجة",
  "developer": "مطوّر",
  "data": "بيانات",
  "database": "قاعدة بيانات",
  "server": "خادم",
  "file": "ملف",
  "folder": "مجلد",
  "download": "تحميل",
  "upload": "رفع",
  "system": "نظام",
  "pengaturan": "إعدادات",
  "jaringan": "شبكة",
  "koneksi": "اتصال",
  "cepat": "سريع",
  "lambat": "بطيء",
  "bagus": "جيد",
  "buruk": "سيئ",
  "hebat": "ممتاز",
  "lemah": "ضعيف",
  "kuat": "قوي",
  "merah": "أحمر",
  "biru": "أزرق",
  "hijau": "أخضر",
  "kuning": "أصفر",
  "hitam": "أسود",
  "putih": "أبيض",
  "abu-abu": "رمادي",
  "jingga": "برتقالي",
  "pink": "وردي",
  "ungu": "بنفسجي",
  "emas": "ذهبي",
  "perak": "فضي",
  "pizza": "بيتزا",
  "makaroni": "معكرونة",
  "atap": "سطح",
  "pintu": "باب",
  "jendela": "نافذة",
  "tembok": "جدار",
  "plafon": "سقف",
  "lantai": "أرضية",
  "dapur": "مطبخ",
  "kamarmandi": "حمام",
  "kamartidur": "غرفة نوم",
  "ruangtamu": "غرفة جلوس",
  "mejakerja": "مكتب عمل",
  "bantal": "وسادة",
  "selimut": "بطانية",
  "rak": "رف",
  "cermin": "مرآة",
  "karpet": "سجادة",
  "tamanrumah": "حديقة منزل",
  "senter": "مصباح يد",
  "amplop": "ظرف",
  "pensil": "قلم رصاص",
  "kertas": "ورقة",
  "penghapus": "ممحاة",
  "serutanpensil": "مبراة",
  "gunting": "مقص",
  "sikatrambut": "فرشاة شعر",
  "odol": "معجون أسنان",
  "AC": "مكيف هواء",
  "remote": "ريموت",
  "alatmusik": "آلة موسيقية",
  "dokter": "طبيب",
  "perawat": "ممرضة",
  "apotek": "صيدلية",
  "obat": "دواء",
  "peredanyeri": "مسكن الألم",
  "suntikan": "حقنة",
  "restoran": "مطعم",
  "pelayan": "نادل",
  "memasak": "طبخ",
  "hidangan": "طبق",
  "dessert": "حلوى",
  "sarapan": "فطور",
  "makansiang": "غداء",
  "makanmalam": "عشاء",
  "tidur": "نوم",
  "bangun": "استيقاظ",
  "istirahat": "راحة",
  "kelelahan": "تعب",
  "kekuatan": "قوة",
  "kecepatan": "سرعة",
  "kegembiraan": "فرح",
  "kesedihan": "حزن",
  "kemarahan": "غضب",
  "ketakutan": "خوف",
  "keheranan": "دهشة",
  "kebahagiaan": "سعادة",
  "senyuman": "ابتسامة",
  "airmata": "دموع",
  "tawa": "ضحك",
  "bercanda": "مزاح",
  "persahabatan": "صداقة",
  "cinta": "حب",
  "pernikahan": "زواج",
  "keluarga": "عائلة",
  "ibu": "أم",
  "ayah": "أب",
  "anaklaki-laki": "ابن",
  "anakperempuan": "ابنة",
  "kakek": "جد",
  "nenek": "جدة",
  "paman (ayah)": "عم",
  "paman (ibu)": "خال",
  "bibi (ayah)": "عمة",
  "bibi (ibu)": "خالة",
  "tetangga": "جار",
  "teman": "صديق",
  "rekankerja": "زميل",
  "gaji": "راتب",
  "kenaikanjabatan": "ترقية",
  "pengalaman": "خبرة",
  "liburan": "إجازة",
  "rencanakerja": "خطة kerja",
  "manajer": "مدير",
  "perusahaanbesar": "شركة كبيرة",
  "start-up": "شركة ناشئة",
  "investor": "مستثمر",
  "penjualan": "مبيعات",
  "pembelian": "شراء",
  "perdagangan": "تجارة",
  "keuntungan": "ربح",
  "kerugian": "خسارة",
  "pengiriman": "توصيل",
  "gudang": "مخزن",
  "penyimpanan": "تخزين",
  "pertumbuhan": "نمو",
  "index": "مؤشر",
  "statistik": "إحصاء",
  "beasiswa": "منحة",
  "ujian": "امتحان",
  "nilai": "نتيجة",
  "tutor": "مدرس خصوصي",
  "gedungaula": "قاعة",
  "laboratorium": "مختبر",
  "cedera": "إصابة",
  "patah": "كسر",
  "radang": "التهاب",
  "infeksi": "عدوى",
  "bengkak / tumor": "ورم",
  "sakitkepala": "صداع",
  "pusing": "دوخة",
  "pingsan": "إغماء",
  "bersin": "عطس",
  "alergi": "حساسية",
  "pernapasan": "تنفس",
  "bernapas": "يتنفس",
  "ventilasi": "تنفس صناعي",
  "oksigen": "أوكسجين",
  "tekanandarah": "ضغط الدم",
  "detaknadi": "نبض",
  "dinginsekali": "برد شديد",
  "panassekali": "حر شديد",
  "haus": "عطش",
  "lapar": "جوع",
  "suaraindah": "صوت جميل",
  "suarakeras": "صوت مرتفع",
  "suarapelan": "صوت منخفض",
  "gema": "صدى suara",
  "leveltinggi": "مستوى عالٍ",
  "levelrendah": "مستوى منخفض",
  "statusaktif": "حالة نشطة",
  "statuspasif": "حالة خاملة",
  "manajemenwaktu": "إدارة الوقت",
  "rencanaharian": "تنظيم يومي",
  "fokusmendalam": "تركيز عميق",
  "gangguanfokus": "تشتيت انتباه",
  "tugasharian": "مهام يومية",
  "daftartugas": "قائمة مهام",
  "prioritastinggi": "أولوية قصوى",
  "jadwalmingguan": "جدول أسبوعي",
  "pencapaiancepat": "إنجاز سريع",
  "produktivitastinggi": "إنتاجية عالية",
  "perencanaansebelumnya": "تخطيط مسبق",
  "tujuanjangkapanjang": "هدف طويل المدى",
  "tujuanjangkapendek": "هدف قصير المدى",
  "tahappertama": "مرحلة أولى",
  "tahapakhir": "مرحلة نهائية",
  "selangkahdemiselangkah": "خطوة خطوة",
  "hasilakhir": "نتيجة نهائية",
  "perhitungantepat": "حساب دقيق",
  "evaluasiharian": "مراجعة يومية",
  "pengembanganberkelanjutan": "تطوير مستمر",
  "perbaikandiri": "تحسين ذاتي",
  "pengaturanfile": "تنظيم ملفات",
  "manajemenproyek": "إدارة مشاريع",
  "komunikasiefektif": "تواصل فعال",
  "dialogkonstruktif": "حوار بنّاء",
  "perbedaankecil": "خلاف بسيط",
  "kesepakatanpenuh": "اتفاق كامل",
  "presentation": "عرض تقديمي",
  "konsultasiprofesional": "استشارة مهنية",
  "tugasresmi": "مهمة رسمية",
  "penjelasandetail": "شرح مفصل",
  "informasiakurat": "معلومات دقيقة",
  "poinpenting": "نقطة مهمة",
  "contohpraktis": "مثال عملي",
  "ringkasanumum": "ملخص عام",
  "kesimpulanfinal": "خلاصة نهائية",
  "dukunganteknis": "دعم فني",
  "solusisiappakai": "حلول جاهزة",
  "setupotomatis": "إعداد تلقائي",
  "percobaangagal": "محاولة فاشلة",
  "cobalagi": "إعادة محاولة",
  "datakurang": "بيانات ناقصة",
  "datavalid": "بيانات صحيحة",
  "filemissing": "ملف ناقص",
  "filecorrupt": "ملف تالف",
  "downloadsukses": "تحميل ناجح",
  "uploadsukses": "رفع ناجح",
  "installsukses": "تثبيت ناجح",
  "setupsukses": "إعداد ناجح",
  "restoreberhasil": "استعادة ناجحة",
  "autorun": "تشغيل تلقائي",
  "forcestop": "إيقاف إجباري",
  "percobaanbaru": "تجربة جديدة",
  "antarmukabaru": "واجهة جديدة",
  "versiterbaru": "نسخة محدثة",
  "rilisanbaru": "إصدار جديد",
  "levelprofesional": "مستوى محترف",
  "pengaturanlanjutan": "إعدادات متقدمة",
  "antarmukasimple": "واجهة بسيطة",
  "antarmukakompleks": "واجهة معقدة",
  "sistemlengkap": "نظام كامل",
  "selesai 100%": "مكتمل 100٪",
  "siapdipakai": "جاهز للاستخدام",
  "ramahpengguna": "سهل الاستخدام",
  "compatiblehp": "متوافق مع الهاتف",
  "compatiblebrowser": "متوافق مع المتصفح",
  "mendukungiPhone": "يدعم iPhone",
  "mendukungSafari": "يدعم Safari",
  "tanpaerror": "بدون أخطاء",
  "tanpamasalah": "بدون مشاكل",
  "siapdeploy": "جاهز للنشر"
}
};