module.exports = {
  AR_ID: {
    "كتب": "menulis",
    "كاتب": "penulis",
    "مكتوب": "tertulis",
    "كتاب": "buku",
    "كتابة": "penulisan",
    "مكتب": "kantor",
    "مكتبة": "perpustakaan",
    "كبير": "besar",
    "صغير": "kecil",
    "جميل": "indah",
    "بيت": "rumah",
    "مدرسة": "sekolah",
    "جامعة": "universitas",
    "مستشفى": "rumahsakit",
    "مدينة": "kota",
    "قرية": "desa",
    "عالم": "ilmuwan",
    "علم": "ilmu",
    "يعلم": "mengetahui",
    "يعلمون": "merekamengetahui",
    "ذهب": "pergi",
    "يذهب": "pergi (sedang)",
    "ذاهب": "sedangpergi",
    "ذهبوا": "merekapergi",
    "رجع": "kembali",
    "يرجع": "kembali (sedang)",
    "راجع": "yangkembali",
    "رجوع": "kembalinya",
    "اكل": "makan",
    "يأكل": "sedangmakan",
    "مأكول": "makananyangdimakan",
    "شرب": "minum",
    "يشرب": "sedangminum",
    "مشروب": "minuman",
    "درس": "belajar",
    "يدرس": "sedangbelajar",
    "مدرس": "guru",
    "تعليم": "pendidikan",
    "معلم": "pengajar",
    "سلام": "perdamaian",
    "سلامة": "keselamatan",
    "مسلم": "muslim",
    "اسلام": "islam",
    "سلام عليكم": "assalamualaikum",
    "كيف حالك": "apakabarmu",
    "بخير": "baik",
    "لغة": "bahasa",
    "عربي": "arab",
    "اندونيسي": "indonesia",
    "ترجمة": "terjemahan",
    "مترجم": "penerjemah",
    "عمل": "kerja",
    "عامل": "pekerja",
    "شركة": "perusahaan",
    "مال": "uang",
    "غني": "kaya",
    "فقير": "miskin",
    "وقت": "waktu",
    "ساعة": "jam",
    "يوم": "hari",
    "أسبوع": "minggu",
    "شهر": "bulan",
    "سنة": "tahun",
    "سماء": "langit",
    "أرض": "bumi",
    "شمس": "matahari",
    "قمر": "bulan (moon)",
    "نجمة": "bintang",
    "بحر": "laut",
    "نهر": "sungai",
    "مطر": "hujan",
    "جو": "cuaca",
    "هواء": "udara",
    "حار": "panas",
    "بارد": "dingin",
    "كاتبون": "parapenulis",
    "كتّاب": "parapenulis (jamak)",
    "كتابات": "tulisan-tulisan",
    "كتاباته": "tulisan-tulisannya",
    "مكتوبات": "surat-surat",
    "كتابي": "bersifatbuku / kitabku",
    "كتابية": "tertulis / dokumenter",
    "كتابيون": "kaumliterasi",
    "كاتبتي": "penulisperempuanku",
    "كتّابِي": "penulisanku",
    "إجابة": "jawaban",
    "سؤال": "pertanyaan",
    "أسئلة": "pertanyaan-pertanyaan",
    "جواب": "jawaban",
    "يجيب": "menjawab",
    "مجيب": "yangmenjawab",
    "مجاوب": "yangmerespon",
    "إجابات": "jawaban-jawaban",
    "سائل": "yangbertanya",
    "مسؤول": "bertanggungjawab",
    "مسؤولية": "tanggungjawab",
    "مسؤوليات": "tanggungjawab (jamak)",
    "مسألة": "perkara / persoalan",
    "مسائل": "perkara-perkara",
    "بحث": "penelitian",
    "يبحث": "mencari / meneliti",
    "باحث": "peneliti",
    "معلومات": "informasi",
    "معلومة": "sebuahinformasi",
    "علماء": "parailmuwan",
    "أعلم": "palingtahu",
    "تعلم": "belajar",
    "يتعلم": "sedangbelajar",
    "تعليمات": "instruksi",
    "مكتشف": "penemu",
    "اكتشاف": "penemuan",
    "يكتشف": "menemukan",
    "مفهوم": "konsep",
    "يفهم": "memahami",
    "فهم": "pemahahan",
    ...
    ...
  },

  ID_AR: {
    "menulis": "كتب",
    "penulis": "كاتب",
    "tertulis": "مكتوب",
    "buku": "كتاب",
    "penulisan": "كتابة",
    "kantor": "مكتب",
    "perpustakaan": "مكتبة",
    "besar": "كبير",
    "kecil": "صغير",
    "indah": "جميل",
    "rumah": "بيت",
    "sekolah": "مدرسة",
    "universitas": "جامعة",
    "rumahsakit": "مستشفى",
    "kota": "مدينة",
    "desa": "قرية",
    "ilmuwan": "عالم",
    "ilmu": "علم",
    ...
    ...
  }
};
